# Butterfly主题配置文件

# 菜单设置
menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  关于: /about/ || fas fa-heart

# 代码设置
highlight_theme: mac light
highlight_copy: true
highlight_lang: true
highlight_shrink: false
code_word_wrap: false

# 社交图标
social:
  fab fa-github: https://github.com/leoda1 || Github
  fas fa-envelope: mailto:20231083510920@buu.edu.cn || Email

# 头像
avatar:
  img: /images/avatar.jpg
  effect: true

# 网站图标设置
favicon: /images/favicon-32x32-next.png

# 顶部导航栏设置
nav:
  logo: 
  display_title: true
  fixed: false

# 主页标语设置
subtitle:
  enable: true
  effect: true
  loop: true
  loopCount: 0
  source: false
  sub:
    - 干中学，学中干
    - AI Infra 技术分享
    - 分享学习经验，记录成长轨迹

# 首页文章节选
index_post_content:
  method: 3
  length: 500

# 图片描述
photofigcaption: true

# 复制设置
copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50

# 本地搜索
local_search:
  enable: true
  preload: false

# 网站副标题
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: AI Infra 技术分享
    button:
      enable: true
      icon: fab fa-github
      text: Github
      link: https://github.com/leoda1
  card_announcement:
    enable: true
    content: 欢迎来到我的博客！这里分享AI基础架构相关的技术文章。
  card_recent_post:
    enable: true
    limit: 5
    sort: date
  card_categories:
    enable: true
    limit: 8
    expand: none
  card_tags:
    enable: true
    limit: 40
    color: false

# 访问人数统计
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 美化配置
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"

# 图片灯箱
fancybox: true

# mermaid
mermaid:
  enable: true
  theme:
    light: default
    dark: dark

# 评论系统 (先禁用)
comments:
  use: 
  text: true
  lazyload: true
  count: false
  card_post_count: false

# 美化页脚
footer:
  owner:
    enable: true
    since: 2025
  custom_text: 
  runtime:
    enable: false

# 右下角按钮
rightside-bottom:
  enable: true 